### ISSUE TITLE
wand_gui doesn’t run properly with python3.8

### ISSUE THREAD

**Issue by bazavano** [OxfordIonTrapGroup/wand#31]
When running the wand_gui with python3.8, the gui does not update when using any of the gui operations (eg fast mode). However, the gui receives updates when other clients (using other py versions) have the fast mode selected, for example.

Debugging in  wand\gui.py:
The fast mode button works:
print(data) in add_async_cb gives ('fast_mode',)
however this doesn’t reach fast_mode_cb

print(self.fut.done()) is True in  add_async_cb. However, print(self.fut.result()) in add_async_cb gives the following error:
File "/home/ion/scratch/wand_new/wand/gui.py", line 123, in add_async_cb
    print(self.fut.result())
  File "/home/ion/scratch/wand_new/wand/gui.py", line 300, in loop
    await asyncio.wait_for(self.wake_loop.wait(),
  File "/home/ion/anaconda3/envs/wand_py38/lib/python3.8/asyncio/tasks.py", line 448, in wait_for
    loop = events.get_running_loop()
RuntimeError: no running event loop

**Comment by hartytp** [comment]
Summarising slack conversations...the behaviour of `wait_for` seems to be different in newer versions of python. Replacing it with an `await` (no timeout) works fine. So it looks like `wait_for` is complaining that no event loop is running, even though await works fine. This feels like a bug somewhere outside of our code (either asyncio or quamash).

Let's try passing our event loop into `wait_for` as a kwarg. That will be depreciated in a future python revision, but let's hope the underlying bug has been fixed before that happens.

**Comment by hartytp** [comment]
cf https://github.com/python/cpython/blob/a1652da2c89bb21f3fdc71780b63b1de2dff11f0/Lib/asyncio/tasks.py#L435

**Comment by hartytp** [comment]
I suspect the issue here is that the `get_event_loop` code here https://github.com/python/cpython/blob/master/Lib/asyncio/events.py is thread specific and this is being called from a coroutine in a qt thread....

@bazavano can you try one thing quickly: at the start of the `loop` function call `set_event_loop` passing in the event loop. If that works can you submit a PR to close this issue. Put a comment next to the line of code that references this issue.

**Comment by bazavano** [comment]
Sending the event loop via `set_event_loop ` at the beginning of the` loop` function doesn't solve the issue and with `print(self.fut.result())` in `add_async_cb` catches the following error when pressing fast mode:
('fast_mode',)
Traceback (most recent call last):
  File "/home/ion/scratch/wand_new/wand/gui.py", line 124, in add_async_cb
    print(self.fut.result())
  File "/home/ion/scratch/wand_new/wand/gui.py", line 124, in add_async_cb
    print(self.fut.result())
  File "/home/ion/scratch/wand_new/wand/gui.py", line 124, in add_async_cb
    print(self.fut.result())
  [Previous line repeated 3 more times]
  File "/home/ion/scratch/wand_new/wand/gui.py", line 302, in loop
    await asyncio.wait_for(self.wake_loop.wait(), next_measurement_in) #, loop = self._gui.loop)
  File "/home/ion/anaconda3/envs/wand_py38/lib/python3.8/asyncio/tasks.py", line 448, in wait_for
    loop = events.get_running_loop()
RuntimeError: no running event loop

**Comment by hartytp** [comment]
uurgh...well, let's add the hack in to pass the event loop into `wait_for`. We can then (a) hop this goes away in some future version of python (prior to that parameter being depreciated) (b) do some debugging inside asyncio to figure out why `get_event_loop` isn't returning the event loop we've set (but if this gets into some qt thread issue, that could be quite non-trivial so I'm not volunteering right away)...

**Comment by bazavano** [comment]
the `loop ` parameter in `wait_for` will be deprecated in py3.10, so this is not a long-term solution, but will do until someone has time to understand the issue better
